# revenue 

rm(list = ls())
getwd()
library(tidyverse)
library(readr)
library(timetk)
library(lubridate)

library(tidyverse)
library(hrbrthemes)
library(kableExtra)

# read pdp 
df <- read_csv("raw/pdp4.csv") %>%
  filter(device_type %in% c('Mobile','Desktop'))%>%
  filter(date <= as.Date('2022-04-24')) %>%
  distinct()


# rtr served
rtr_served  <- df %>%
  filter(offer_typ == 'survey', etyp == 'CRDIMPR') %>%
  distinct() %>%
  group_by(date, ext_user_id) %>%
  summarise(rtr_served = n())


# rtr earn 
df_rtr <- df %>% 
  filter(pts_source=='rtr') %>%
  mutate(rtr_type = if_else(brand_id=='843b07c3-49b0-432d-82af-d2bfdffcb6a8',
                            'Free','Paid'
  )) %>% distinct()

paid_rtr <- df_rtr %>%
  filter(rtr_type=='Paid') %>%
  group_by(date,ext_user_id) %>%
  summarise(rtr_earned_paid = n()) %>%
  ungroup()

free_rtr <- df_rtr %>%
  filter(rtr_type=='Free') %>%
  group_by(date,ext_user_id ) %>%
  summarise(rtr_earned_free = n()) %>%
  ungroup() 



time <- df %>% select(date) %>%
  filter(date >= as.Date('2022-04-01')) %>%
  distinct() 

df_revenue <- time %>%
  left_join(rtr_served) %>%
  left_join(paid_rtr) %>%
  left_join(free_rtr)

df_revenue[is.na(df_revenue)] <- 0
df_revenue$revenue <- df_revenue$rtr_earned_paid * 2
df_revenue  <- df_revenue %>% 
  mutate(ratio = round(
  (df_revenue$rtr_earned_paid + df_revenue$rtr_earned_free) / df_revenue$rtr_served,
  2),
  buckets = case_when(
    ratio <= 0.10 ~ '[0 - 0.1]',
    ratio <= 0.2 & ratio > 0.10 ~ '(0.1 - 0.2]',
    ratio <= 0.3 & ratio > 0.20 ~ '(0.2 - 0.3]',
    ratio <= 0.4 & ratio > 0.30 ~ '(0.3 - 0.4]',
    ratio <= 0.5 & ratio > 0.4 ~ '(0.4 - 0.5]',
    ratio <= 0.6 & ratio > 0.50 ~ '(0.5 - 0.6]',
    ratio <= 0.7 & ratio > 0.60 ~ '(0.6 - 0.7]',
    ratio <= 0.8 & ratio > 0.70 ~ '(0.7 - 0.8]',
    ratio <= 0.9 & ratio > 0.80 ~ '(0.8 - 0.9]',
    TRUE ~ '(0.9 - 1.0]'
  ),
  orderby = case_when(
    buckets == '[0 - 0.1]' ~ 1,
    buckets ==  '(0.1 - 0.2]' ~ 2,
    buckets =='(0.2 - 0.3]' ~ 3,
    buckets == '(0.3 - 0.4]' ~ 4,
    buckets == '(0.4 - 0.5]' ~ 5,
    buckets == '(0.5 - 0.6]' ~ 6,
    buckets == '(0.6 - 0.7]' ~ 7,
    buckets == '(0.7 - 0.8]' ~ 8,
    buckets ==  '(0.8 - 0.9]' ~9,
    buckets== '(0.9 - 1.0]' ~ 10))

df_revenue_ <- df_revenue %>%
  group_by(buckets,orderby) %>%
  summarise(n_users = n_distinct(ext_user_id),
            rtr_earned_paid= sum(rtr_earned_paid),
            rtr_earned_free = sum(rtr_earned_free)) %>%
  mutate(n_rtr = rtr_earned_free + rtr_earned_paid) %>%
  ungroup()
# plots
par(mfrow=c(2,2))    # set the plotting area into a 1*2 array


df_revenue_ %>%
  filter(!is.na(n_users)) %>%
  arrange(n_users) %>%
  ggplot( aes(x=reorder(buckets,orderby), y=n_users) ) +
  geom_bar(stat="identity", fill="#69b3a2") +
  coord_flip() +
  geom_text(
    aes(label = n_users), 
    size = 3, fontface = "bold", family = "Fira Sans"
  ) +
  theme_ipsum() +
  theme(
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.position="none"
  ) +
  xlab("RTR taken / RTR served") +
  ylab("# Users")

 # rtrs 

df_revenue_ %>%
  filter(!is.na(n_rtr)) %>%
  arrange(n_users) %>%
  ggplot( aes(x=reorder(buckets,orderby), y=n_rtr) ) +
  geom_bar(stat="identity", fill="#69b3a2") +
  coord_flip() +
  geom_text(
    aes(label = n_rtr), 
    size = 3, fontface = "bold", family = "Fira Sans"
  ) +
  theme_ipsum() +
  theme(
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    legend.position="none"
  ) +
  xlab("RTR taken / RTR served") +
  ylab("# RTR taken")


# df_revenue %>%
#   group_by(date) %>%
#   summarise(ratio =mean(ratio)) %>%
#   ungroup() %>%
#   ggplot(aes(date, ratio)) +
#   geom_line()+
#   theme_ipsum() +
#   theme(
#     panel.grid.minor.y = element_blank(),
#     panel.grid.major.y = element_blank(),
#     legend.position="none"
#   )

# df_revenue %>%
#   group_by(date) %>%
#   summarise(revenue =sum(revenue)) %>%
#   ungroup() %>%
# ggplot(aes(date, revenue)) +
#   geom_line()

df_revenue %>%
  group_by(date) %>%
  summarise(revenue =sum(revenue)) %>%
ggplot(aes(date, revenue, group=1))+
  geom_line(color="#69b3a2", size=1.5)+
  geom_point(size=4,color="#69b3a2")+
  geom_text(
    aes(label = revenue), 
    size = 3, fontface = "bold", family = "Fira Sans"
  ) +
  theme_ipsum()+
  labs(x="Date", y="Revenue generated by paid RTR($)")
